# Generated by Django 4.1.3 on 2022-11-16 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_average_critics_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_critics_rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
