# Generated by Django 4.1.3 on 2022-11-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_average_critics_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('model_name', models.CharField(choices=[('Book', 'Book'), ('Author', 'Author')], max_length=30)),
            ],
        ),
    ]
